"""Add meta_data column to attachments table

Revision ID: ed6ff66bafc9
Revises: f024b1dbf16b
Create Date: 2025-11-05 17:16:44.596781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'ed6ff66bafc9'
down_revision = 'f024b1dbf16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 檢查欄位是否已存在，避免重複新增
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('attachments')]
    
    if 'meta_data' not in columns:
        op.add_column('attachments', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 檢查欄位是否存在再刪除
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('attachments')]
    
    if 'meta_data' in columns:
        op.drop_column('attachments', 'meta_data')
    # ### end Alembic commands ###
