"""Add meta_data column to attachments table

Revision ID: ed6ff66bafc9
Revises: f024b1dbf16b
Create Date: 2025-11-05 17:16:44.596781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6ff66bafc9'
down_revision = 'f024b1dbf16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'meta_data')
    # ### end Alembic commands ###
